### PR TITLE
add schema_from_csv() to address issue #108

### PR DESCRIPTION
**Pull request by jeffbrennan**
sorry I messed up my fork

readding feature from a clean branch

----

addresses #108 

Added a pretty barebones implementation of this. Example is documented in the readme.

Please let me know if you have any feedback!

### CODE REVIEW

**Comment by MrPowers** [comment]
Here's the current test data:

```
name,type,nullable,metadata
person,string,FALSE,{"description":"The person's name"}
address,string,TRUE,{"description":"The person's address"}
phoneNumber,string,TRUE,{"description":"The person's phone number"}
age,int,FALSE,{"description":"The person's age"}
```

Can we update it to be something like this:

```
name,type,nullable,metadata
person,string,false,{"description":"The person's name"}
address,string,TRUE,
phoneNumber,string,TRUE,{"description":"The person's phone number"}
age,int,FALSE,{"description":"The person's age"}
```

That way we can verify that `nullable` isn't case sensitive and that this doesn't blow up if metadata is empty.

I think `nullable` and `metadata` should both be completely optional.  Does this function work if those columns are missing from the CSV?

**Comment by jeffbrennan** [comment]
@MrPowers updated the schema test file and schema_from_csv() function to handle missing nullable and metadata fields. 

`null_str.lower()` handled upper case and title case boolean values. 

One thing I noticed during testing, the test file and expected schema threw a `SchemasNotEqual` error (because of differences in the optional metadata), but the helper dataframe didn't visualize that. I'm down to work on adding that  to chispa unless that was an intentional design choice.

image

**Comment by MrPowers** [comment]
@jeffbrennan - yea, that'd be a great addition to chispa.  Another user [asked for this last week](https://github.com/MrPowers/chispa/issues/70) as well.  Thank you!

**Comment by MrPowers** [comment]
@jeffbrennan - here's a PR to add this option to chispa: https://github.com/MrPowers/chispa/pull/74

**Comment by MrPowers** [comment]
I am going to merge this and then push up some test cleanup.  Thanks for this contribution.

**Pull request merged**
