### PR TITLE
Split-dependencies-into-groups

### LINKED ISSUE #128: Split dev-dependencies into multiple groups
Concept of dev-dependencies will be deprecated, migration to notion of groups is necessary.
Currently all development dependencies besides docs are in single group. Split them into multiple groups such as development, linting, testing, and docs.
Add Makefile for common commands.

### PR DESCRIPTION
**Pull request by dinjazelena**
Closes #128 

a). Split dev-dependencies into: 
    1. development group
    2. testing group
    3. linting group
    4. docs group

b) Created Makefile with few common commands.

c) Updated ruff.yaml
    1. Added trigger for every push(lint should always run)
    2. Renamed job to Lint(Since i guess in future there should be black and mypy beside ruff)

### CODE REVIEW

**Comment by dinjazelena** [comment]
@MrPowers , Is there a reason for having exact versions of pytest, chipsa,ruff, semver?

I did put caret sign so pytest were updated from 7.4.0 to 7.4.2 and chipsa from 0.9.2 to 0.9.3.

**Comment by dinjazelena** [comment]
Ruff only enables Pycodestyle and Pyflakes which is kinda very shallow pythonic pep8 check. You should
select = ['ALL'] and then ignore the ones according to your preferences.

**Comment by dinjazelena** [comment]
@MrPowers , Is there a specific reason for using custom gh action for running ruff? Do u plan introducing mypy and black?

**Comment by SemyonSinchenko** [comment]
The problem here is we are not able to test new actions until we merge it. But I do not see a big problem even if we break CI. So, LGTM.

@dinjazelena May we add to linting also a spell-checking for a README.md file?

**Comment by dinjazelena** [comment]
@SemyonSinchenko , what exactly can we use for spell-checking?

**Comment by SemyonSinchenko** [comment]
Something like [this](https://github.com/hcodes/yaspeller) or any similar solution.

**Comment by MrPowers** [comment]
LGTM

**Comment by MrPowers** [comment]
@dinjazelena - this project also needs dependencies split into groups: https://github.com/pyspark-ai/pyspark-ai/issues/137

This is a good opportunity to contribute to another project that's run by the PySpark core devs if you're interested.

Thank you for the contribution.

**Pull request merged**
