### PR TITLE
DataFrame#transform method added in Spark 3

### PR DESCRIPTION
**Pull request by NikhilGupta178**
Added code is tested for PySpark 3.3.2

### CODE REVIEW

**Comment by MrPowers** [comment]
@NikhilGupta178 - thanks for submitting this.  We'll need to make sure this function works as intended for PySpark 2, PySpark 3.2, and PySpark 3.3 (because PySpark 3.3 changed the method signature again).  Have you tested out this version for different PySpark versions to make sure it's working as intended?  This is a public facing function and we want to make sure that it works for all our users correctly.  Let me know!

**Comment by MrPowers** [comment]
@SemyonSinchenko - can you please test this one in detail?  We need to be careful about this because it could break public interfaces, thanks!

**Comment by SemyonSinchenko** [comment]
So I made a check and create a code snippet:
```python
import warnings
from pyspark.sql.dataframe import DataFrame

def _ext_function(self, f):
    warnings.warn(
        "Extensions may be removed in the future versions of quinn. Please use explicit functions instead",
        category=DeprecationWarning,
        stacklevel=2
    )
    return f(self)

DataFrame.transform = getattr(DataFrame, "transform", _ext_function)
```
I run this code under PySpark 2.4.8:
image

And under latest PySpark:
image


As you can see in latest PySpark there is no replacement of existed method (because there is no warning in output). So it works well.

@MrPowers I think we can merge this and also do in the same way with other `extensions`

**Review by SemyonSinchenko — APPROVED** [review]

**Comment by MrPowers** [comment]
@SemyonSinchenko - thanks for the detailed QA.

@NikhilGupta178 - thanks for the contribution.

**Pull request merged**
