### PR TITLE
fix ruff lint

### PR DESCRIPTION
**Pull request by jeffbrennan**
@MrPowers this should get rid of the scary x

changes to `split_columns.py` shouldn't affect anything
not familiar with the row.get() method in `schema_helpers.py` but the tests cover mode="permissive" cases and they pass for me

### CODE REVIEW

**Comment by jeffbrennan** [comment]
updated pyproject.toml after doing some investigation and reading #187 
image

**Comment by SemyonSinchenko** [comment]
I'm afraid that they may introduce new rules in updates, and we will face cases when we start getting failing lint on old codebase one day

**Comment by jeffbrennan** [comment]
Yeah that makes sense, in that case we should specify a ruff version in the ci setup

**Comment by SemyonSinchenko** [comment]
@jeffbrennan Is it ready for merging?

**Comment by jeffbrennan** [comment]
@SemyonSinchenko 

there's been a lot of changes to the main repo since these changes. I'll close this PR and look at setting a ruff version in CI. If there's still formatting issues afterwards I'll take care of those

**Pull request closed without merging**
