### PR TITLE
Added function business_days_between

### PR DESCRIPTION
**Pull request by fpvmorais**
As discussed on https://github.com/MrPowers/quinn/issues/84

Here's my proposition

Thanks

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
Looks great! Nice work! One question: may we add an option to pass inside such a function business calendar as a PySpark DataFrame with two columns (date, is_business_day_flag)? Cause in my experience it is interesting not only count Mon-Fri but use country-specific business calendar.

**Comment by fpvmorais** [comment]
Sure. Makes total sense. We could also think about using https://github.com/dr-prodigy/python-holidays to obtain those holidays.
This library is used on a lot of open source tools.

**Comment by SemyonSinchenko** [comment]
> Sure. Makes total sense. We could also think about using https://github.com/dr-prodigy/python-holidays to obtain those holidays.
> This library is used on a lot of open source tools.

Great idea!

**Comment by fpvmorais** [comment]
)do you need me to do anything else to get this merged?

**Comment by SemyonSinchenko** [comment]
@fpvmorais Hello! I'm so sorry that I need to say this but please, may you make merge from master to your branch and resolve conflicts? It should be easy. The problem was we had a lot of open PRs and order of merging wasn't trivial. Thank you for this contribution!

**Review by SemyonSinchenko — APPROVED** [review]

**Comment by SemyonSinchenko** [comment]
Thank you for this contribution!

**Pull request merged**
