### PR TITLE
Add templates for feature-request, bug-report, docs-improvement

### LINKED ISSUE #164: Add template design for requesting features, bugs, docs changes, and PR
Title

### PR DESCRIPTION
**Pull request by dinjazelena**
When creating Issue, template will be provided to users to have standardized way of tackling issues and discussion.
closes #164

### CODE REVIEW

**Comment by dinjazelena** [comment]
@MrPowers, hey so this is kinda hard to test, cos it requires merge to main in order to take full effect. I can show u with screenshots how it looks like? But in general for bug-reports:
1. reproduce minimal example of bug
2. issue description
3. expected behavior

Check if u are using latest quinn version.
Adds bug label to issue. and BUG: suffix in order to filter out all issues.

**Comment by dinjazelena** [comment]
@MrPowers , @SemyonSinchenko , so its very generic templates for issues, so i think we ca just merge it and check it out and just have fixes if there is something that u want to change. Otherwise i also added it to test repo so u can check how it looks:
https://github.com/dinjazelena/test-issues Go Issue and have a look.

**Comment by dinjazelena** [comment]
@SemyonSinchenko , so its totally up to us and our imagination really. Maybe for questions we could have discussion panel 
https://docs.github.com/en/discussions/quickstart.
But i could see it being just irrelevant cos its not like its so huge community, and kinda more verbose and transparent if its in Issue.
So up to u to decide really.

**Comment by SemyonSinchenko** [comment]
@MrPowers what do you think about this?

**Comment by SemyonSinchenko** [comment]
@dinjazelena May you also update CONTRIBUTING.md file? Tnx

**Comment by SemyonSinchenko** [comment]
@dinjazelena Is there any progress here? Do you need help? In the case if you wont have time for it anymore, please notify us here about it. It is absolutely OK, we just reassign this ticket in such a case!

**Comment by dinjazelena** [comment]
Templates for Issues and PR is done.

**Review by SemyonSinchenko — APPROVED** [review]
LGTM

**Review by MrPowers — APPROVED** [review]
LGTM

**Pull request merged**
