### PR TITLE
Added flake8

### PR DESCRIPTION
**Pull request by squerez**
Tackles issue https://github.com/MrPowers/quinn/issues/58.

### CODE REVIEW

**Comment by MrPowers** [comment]
Thanks for adding this.  Pinged Robert to review since he knows more about this than I do.  Really appreciate this.  Will make sure it gets reviewed & merged.

**Comment by robertkossendey** [comment]
@MrPowers LGTM!

**Comment by MrPowers** [comment]
Thanks for the contribution @squerez

**Comment by MrPowers** [comment]
@squerez @robertkossendey - actually, this build failed.  Can you take a look?

**Comment by robertkossendey** [comment]
@MrPowers ah, it is because the code is not flake8 compliant yet. We should change the code accordingly. I would also suggest to add pre-commit hooks that run flake8 on commit.

**Comment by MrPowers** [comment]
@ajitkshirsagar - yea, that sounds good.  Can you make a new issue?  I will assign it to you!

**Comment by ajitkshirsagar** [comment]
@MrPowers I have created this [issue](https://github.com/MrPowers/quinn/issues/69), please assign it to me.

**Pull request merged**
