### PR TITLE
Add UUID5 generating function

### PR DESCRIPTION
**Pull request by YevIgn**

### CODE REVIEW

**Review by SemyonSinchenko — APPROVED** [review]
LGFM

**Comment by SemyonSinchenko** [comment]
@MrPowers JFYI

**Comment by MrPowers** [comment]
How does this differ from the built-in UUID function?

**Comment by MrPowers** [comment]
I'm looking at [this blog post](https://pythonisrad.medium.com/uuids-in-pyspark-53fd3935d093).  I actually like this implementation because it looks like no UDF Is required.  This looks really cool actually.

**Comment by YevIgn** [comment]
> How does this differ from the built-in UUID function?

> I'm looking at [this blog post](https://pythonisrad.medium.com/uuids-in-pyspark-53fd3935d093). I actually like this implementation because it looks like no UDF Is required. This looks really cool actually.

Yes, built-in is only for random UUIDs, this was done exactly for the case described in blog post linked - actually idea was born initially as an attempt to avoid Pandas / PyArrow dependency. On Spark 3.4.0+ OVERLAY (`overlay()` in functions.py) can be used instead of one of the CONCAT+SUBSTRING - here not used as Quinn supports Spark 2.x as well (`overlay` saves at least one string allocation as far as it's implemented in Spark 3.4.0 and pushdown should work for it for the DBs where OVERLAY is supported).

Performance-wise pure PySpark function beats Pandas UDF, but only slightly in the trivial "benchmarks" we have conducted, both are faster than non-vectorised Python UDF by a significant margin (if it matters of course).

Implementation itself is just reverse-engineering of `uuid5()` generation from stdlib + extra string argument. I tried to use bitwise operations on columns directly, but they weren't worth the effort figuring correct conversion process (and ChatGPT apparently struggled to help with this task as well).

For variant setting only single character / byte can be extracted from generated hash, but it will incur additional CONCAT call further so I settled on the function in PR.

**Comment by MrPowers** [comment]
@YevIgn - thanks for the contribution.

**Pull request merged**
