### PR TITLE
Add MKDocs

### LINKED ISSUE #71: Using GH-Pages for hosting documentation of API
My suggestion is to use GH-Pages for API Docs (instead of README.md).

There are few options:
1. Use `mkdocs`: [deploying MKDocs to GHP](https://www.mkdocs.org/user-guide/deploying-your-docs/#github-pages)
2. Use `sphinx`: [GH Action to deploy Sphinx to GHP](https://github.com/marketplace/actions/sphinx-to-github-pages)

Anyway there will be a day when amount of public functions and helpers will be so big that it is not fin into a single README page...

P.S. Also it will solve the problem with outdated documentation because we will use functions/methods signatures and docstrings to update documentation as a CI/CD step after push into main branch.

### PR DESCRIPTION
**Pull request by SemyonSinchenko**
What was done:

- mkdocs.yaml
- changes in pyproject.toml
- just to make tests I added two docstrings
- fixed logo-link inside README.md
- auto-doc pyython script
- some additions to gitignore (including site)

To run tests it is enough to do the following:

1. checkout to the branch
2. poetry install --with mkdocs
3. poetry run mkdocs serve

**I'm not sure that GH Action will work and I cannot test it now**

**To be able to use MKDocs I might increase Py version to >=3.7**

But version shouldn't affect anything in runtime... Anyway Python 3.7 is not
supported already. So no reason to support Python 3.5-3.6.

 On branch mkdocs
 Changes to be committed:
	new file:   .github/workflows/mkdocs.yml
	modified:   .gitignore
	modified:   README.md
	new file:   docs/gen_ref_pages.py
	new file:   docs/index.md
	new file:   mkdocs.yml
	modified:   poetry.lock
	modified:   pyproject.toml
	modified:   quinn/__init__.py
	modified:   quinn/dataframe_helpers.py
	modified:   quinn/schema_helpers.py

close #71

### CODE REVIEW

**Comment by SemyonSinchenko** [comment]
1. We cannot test GH Action until this is not merged (there is no MKDocs action now)
2. I used SPHINX docstrings-style as discussed in #13
3. It is a very big PR and it is more topic of discussion instead of read-to merge work

P.S. In #64 author used different style of dosctrings (Numpy-style)!

**Comment by MrPowers** [comment]
These look great, exciting progress.

Some API docs pages are populated:

Screen Shot 2023-03-09 at 6 05 49 PM

Others are empty:

Screen Shot 2023-03-09 at 6 06 04 PM

But in general, this looks like a great step in the right direction!

What are the next steps?

**Comment by SemyonSinchenko** [comment]
> What are the next steps?

1. We should fix the style of docstrings (in #13 you suggested `sphinx`)
2. If you want to change a theme or add additional plugin I can do it now

After that we can merge this and try to run GH Action (it will appear only after merge).

**Comment by SemyonSinchenko** [comment]
> Others are empty:

The problem is MKDocs doesn't parse functions without docstrings. It is strange because I turned the flag `show_if_no_docstring: true`. But I have no more ideas how to deal with it. After adding a docstring function will appear and I checked it by adding docstring to two functions in `dataframe_helpers.py`

**Comment by MrPowers** [comment]
@SemyonSinchenko:

> We should fix the style of docstrings (in https://github.com/MrPowers/quinn/issues/13 you suggested sphinx)

You're right, I did suggest that comment style in #13.  I'm not married to that suggestion at all.  Do you think the spynx style comments are the best or do you prefer another syntax?

> If you want to change a theme or add additional plugin I can do it now

I have no thoughts on themes.  In general, I prefer to limit the number of plugins to the bare minimum and only include plugins that add needed features (not nice to haves).

> The problem is MKDocs doesn't parse functions without docstrings. It is strange because I turned the flag show_if_no_docstring: true. But I have no more ideas how to deal with it. After adding a docstring function will appear and I checked it by adding docstring to two functions in dataframe_helpers.py

We can just add another issue to get all the docstrings added.  Let's not block this progress on missing docstrings or the show_if_no_docstring: true weirdness.  My preference is to stand these docs up in production and then iterate.

**Comment by SemyonSinchenko** [comment]
@MrPowers I'm OK with any format of docstrings and using the same format as in PySpark is a good idea. If all are OK with it we can close #13 and pin `sphinx`. After that we can merge this PR and start filling docstrings for public methods.

**Comment by MrPowers** [comment]
@SemyonSinchenko - ok, closed #13.  Let me know when sphinx is pinned and I can merge.  Thank you!

**Comment by SemyonSinchenko** [comment]
@MrPowers I've done here.

1. I added a short remark about code-style to README
2. I added poetry cache to CI

It is ready for a review.

**Comment by SemyonSinchenko** [comment]
@MrPowers Should I merge it?

**Comment by MrPowers** [comment]
@SemyonSinchenko - merged this in.  What's the URL where we should see the docs?  Thanks for doing all this work!

**Comment by bjornjorgensen** [comment]
> 1. We cannot test GH Action until this is not merged (there is no MKDocs action now)
> 2. I used SPHINX docstrings-style as discussed in [Use PySpark documentation conventions to document the public interface #13](https://github.com/MrPowers/quinn/issues/13)
> 3. It is a very big PR and it is more topic of discussion instead of read-to merge work
> 
> P.S. In #64 author used different style of dosctrings (Numpy-style)!

Yes, I dont know what to use here..

**Pull request merged**
