### PR TITLE
Add maintainers to pyproject.toml & update CONTRIBUTING.md with ruff setup for IDEs (#173 and #163)

### PR DESCRIPTION
**Pull request by nijanthanvijayakumar**
## Proposed changes

**Related to #173, add maintainers to `pyproject.toml` file**

* Add a `maintainers` section below the `authors` section.
* Include the names and contact information of the maintainers (first version only).
* Use the format `name <email>` for each maintainer.
* Add a comment above the `maintainers` section to indicate its purpose.

**Related to #163, following changes have been made in the file:**

* Remove mention of Black from the CONTRIBUTING.md
* Add instructions on how to add ruff to VSCode
* Add instructions on how to add ruff to PyCharm

## Types of changes

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update (if none of the other choices apply)

## Further comments
* Since I was working on two issues and merged them to the main branch on the repo I forked, both the changes have started to appear in this PR. Hence, closes the issues #163  and #173 .
* Regarding the maintainers update, I have added only @SemyonSinchenko to the maintainers list for now. Please let me know if any others should be added to the list in this same PR. PR checks/GitHub actions have passed when I tried merging to my `master/main` branch. Kindly review & merge.

### CODE REVIEW

**Comment by nijanthanvijayakumar** [comment]
@MrPowers and @SemyonSinchenko  - please let me know the list of **maintainers** of this project, so that I can update the `pyproject.toml` with that list.

Also, let me know if [this section](https://github.com/MrPowers/quinn/blob/main/CONTRIBUTING.md?plain=1#L90-L93) in `CONTRIBUTING.md` file should also be updated with that relevant list?

**Review by SemyonSinchenko — APPROVED** [review]
LGTM

**Comment by SemyonSinchenko** [comment]
> Also, let me know if [this section](https://github.com/MrPowers/quinn/blob/main/CONTRIBUTING.md?plain=1#L90-L93) in CONTRIBUTING.md file should also be updated with that relevant list?

We can delete this section because from now we have this information in `pyproject.toml`. @MrPowers @jeffbrennan what do you think?

**Comment by nijanthanvijayakumar** [comment]
> > Also, let me know if [this section](https://github.com/MrPowers/quinn/blob/main/CONTRIBUTING.md?plain=1#L90-L93) in CONTRIBUTING.md file should also be updated with that relevant list?
> 
> We can delete this section because from now we have this information in `pyproject.toml`. @MrPowers @jeffbrennan what do you think?

Ok once confirmed, I will delete this section from the `CONTRIBUTING.md` to update this PR.

**Review by MrPowers — APPROVED** [review]
LGTM, thanks!

**Comment by SemyonSinchenko** [comment]
@nijanthanvijayakumar ping me when you are done and I will merge it.

**Comment by nijanthanvijayakumar** [comment]
> @nijanthanvijayakumar ping me when you are done and I will merge it.

Hello @SemyonSinchenko - I'm done with the changes. Thought I was supposed to wait for @jeffbrennan's approval.

**Comment by nijanthanvijayakumar** [comment]
@SemyonSinchenko - are you able to merge this PR?

**Pull request merged**
